# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 05:33
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('modi', models.IntegerField()),
                ('country_co', models.CharField(max_length=11)),
                ('counting_p', models.CharField(max_length=10)),
                ('key_2000', models.CharField(max_length=10)),
                ('e_roads', models.CharField(max_length=9)),
                ('e_road2000', models.CharField(max_length=10)),
                ('aadt_2000', models.IntegerField()),
                ('length', models.IntegerField()),
                ('aadt_1995', models.IntegerField()),
                ('type2', models.CharField(max_length=5)),
                ('id_field', models.IntegerField()),
                ('coun_p2005', models.CharField(max_length=10)),
                ('key_2005', models.CharField(max_length=8)),
                ('e_road2005', models.CharField(max_length=10)),
                ('aadt_2005', models.IntegerField()),
                ('code_imd', models.FloatField()),
                ('thick_mm', models.FloatField()),
                ('thick_15', models.FloatField()),
                ('thick_25', models.FloatField()),
                ('thick_50', models.FloatField()),
                ('thick_15_m', models.IntegerField()),
                ('thick_25_m', models.IntegerField()),
                ('thick_50_m', models.IntegerField()),
                ('sense_aadt', models.IntegerField()),
                ('type3', models.CharField(max_length=5)),
                ('peatge', models.CharField(max_length=2)),
                ('buff_dist', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=-1)),
            ],
        ),
    ]
