# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 10:15
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20161231_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scalerank', models.IntegerField()),
                ('featurecla', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('abbrev', models.CharField(max_length=4)),
                ('location', models.CharField(max_length=50)),
                ('gps_code', models.CharField(max_length=254)),
                ('iata_code', models.CharField(max_length=254)),
                ('wikipedia', models.CharField(max_length=254)),
                ('natlscale', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='roadnetwork',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=0),
        ),
    ]
