# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 10:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_auto_20161231_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadnetwork',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=0),
        ),
    ]
