# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20161231_1018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoadNetwork',
        ),
    ]
