# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 10:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_delete_roadnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrbanAreaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scalerank', models.IntegerField()),
                ('featurecla', models.CharField(max_length=50)),
                ('area_sqkm', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
