# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 05:16
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_auto_20161231_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBoundaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid_ne_10m', models.IntegerField()),
                ('scalerank', models.FloatField()),
                ('featurecla', models.CharField(max_length=32)),
                ('note_field', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('adm0_usa', models.IntegerField()),
                ('adm0_left', models.CharField(max_length=100)),
                ('adm0_right', models.CharField(max_length=100)),
                ('adm0_a3_l', models.CharField(max_length=3)),
                ('adm0_a3_r', models.CharField(max_length=3)),
                ('sov_a3_l', models.CharField(max_length=3)),
                ('sov_a3_r', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=50)),
                ('labelrank', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
