# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 05:23
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_adminboundarymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminboundarymodel',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
        ),
    ]
